### ISSUE TITLE
NoGatewayAvailableException::getLastException有问题

### ISSUE THREAD

**Issue by Veitor** [overtrue/easy-sms#110]
```
return $this->exceptions[end($this->exceptions)];
```

这句写错了

**Comment by overtrue** [comment]
@Veitor 错在哪里？

**Comment by Veitor** [comment]
$notKey = end($this->exceptions); 会返回最后一个元素的值啊
 再用取数组的形式$this->exceptions[$notKey]是要报错的啊，$notKey不是数组的键

所以$this->exceptions[end($this->exceptions)];这个不对

**Comment by overtrue** [comment]
@Veitor sorry, 我的锅，把它与 `key` 记成一样了。已改正，感谢提醒！:+1:
