### ISSUE TITLE
腾讯云sms,短信发送成功,内容含有[null]

### ISSUE THREAD

**Issue by lianghongle** [overtrue/easy-sms#119]
在使用easy-sms（腾讯云sms）的时候，使用模板发送的短信，短信发送是成功的。但是，短信中总会出现个[null]，不知道是什么原因。例如（【某某科技】[null]1234为您的验证码，请5分中内使用。模板中1234和5分钟的5是参数。）

**Comment by overtrue** [comment]
已经修复：https://github.com/overtrue/easy-sms/pull/120
