### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by nelsonsun** [overtrue/easy-sms#139]
![_032](https://user-images.githubusercontent.com/26363174/45543253-ad543a80-b846-11e8-8648-c4c1b9c06946.png)

PHP 版本: PHP 7.2.6
OS: ubuntu 18.04

**Comment by overtrue** [comment]
https://github.com/overtrue/easy-sms/commit/d7e8fd6d6e2919787295020aa976ae08f39c7b9d

**Comment by overtrue** [comment]
请升级到 1.1.6

**Comment by nelsonsun** [comment]
ok,thanks.
