### ISSUE TITLE
阿里可用余额不足

### ISSUE THREAD

**Issue by xzhonour** [overtrue/easy-sms#140]
阿里可用余额不足 All the gateways have failed?

**Comment by cunheise** [comment]
try AliyunrestGateway.php

**Comment by overtrue** [comment]
@xzhonour 有什么疑问吗？

**Comment by overtrue** [comment]
所有网关都尝试发送失败就会抛出异常，文档上已经说明过了。

**Comment by xzhonour** [comment]
没什么疑问了，后来看到了！谢谢！



 ------------------原始邮件 ------------------
发件人：安正超 <notifications@github.com>
日期：2018-09-25 09:41:01
收件人：overtrue/easy-sms <easy-sms@noreply.github.com>
抄送：DonSen <myhonour@jishuwan.com>, Mention <mention@noreply.github.com>
主题：Re: [overtrue/easy-sms] 阿里可用余额不足 (#140)
所有网关都尝试发送失败就会抛出异常，文档上已经说明过了。

**Comment by overtrue** [comment]
好的

DonSen <notifications@github.com>于2018年9月25日 周二上午9:42写道：
