### ISSUE TITLE
不支持发送数组了么

### ISSUE THREAD

**Issue by lyyhd** [overtrue/easy-sms#146]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/16233666/49064679-a1c5bc80-f256-11e8-8d67-b371b891a409.png">

**Comment by overtrue** [comment]
以前支持数组？

**Comment by lyyhd** [comment]
超哥好，以前没有格式化手机号这一步，直接传$to数组 到网关，然后我自己实现的网关批量发送，现在我想实现批量发送该怎么做呢？

**Comment by overtrue** [comment]
要不你先用遍历发送，后面我改版的时候增加自定义方法支持怎么样？

**Comment by lyyhd** [comment]
👌，感谢超哥耐心解答
