### ISSUE TITLE
网关错误如何打印日志

### ISSUE THREAD

**Issue by zengonly** [overtrue/easy-sms#155]
超哥，不好意思，没描述清楚
![image](https://user-images.githubusercontent.com/21103564/50158494-3a5bd380-030f-11e9-970e-3532b25d9cca.png)
这是现在代码里（发送短信正常）
之前报这个错误
All the gateways have failed. You can get error details by `$exception->getExceptions()` 
当时代码是这样
![image](https://user-images.githubusercontent.com/21103564/50158827-1f3d9380-0310-11e9-9474-ae6762ad8aec.png)
应该是捕获错误那出问题了，导致内存溢出

**Comment by overtrue** [comment]
> "错误调试，是该如何配置"
不明白你在说啥

**Comment by klmahua** [comment]
遇到同样的错误提示，，，不知道问题出在哪里

**Comment by overtrue** [comment]
@klmahua `打印 $exception->getExceptions()`
