### ISSUE TITLE
可以发布一个laravel版的么？方便使用。

### ISSUE THREAD

**Issue by OranTing** [overtrue/easy-sms#160]
谢谢。

**Comment by OranTing** [comment]
很期待你的大作，overtrue出品，必属精品。
目前没有一款很好用的laravel的 Provider。
toplan/laravel-sms 很久没更新了。
ibrandcc/laravel-sms 这是是用的你的easy-sms，但是功能单一，只能发送验证码，并且不能指定模板ID，模板ID写死在了config里面。

**Comment by overtrue** [comment]
@OranTing 😆

**Comment by yangliulnn** [comment]
@OranTing 可以看看我这个，使用 easy-sms 发送 laravel 通知
[https://github.com/yangliulnn/easysms-notification-channel](https://github.com/yangliulnn/easysms-notification-channel)

**Comment by CocoaJerry** [comment]
确实，16年我们就开始用的laravel-sms，但是这个已经有两年多没更了

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-easy-sms
