### ISSUE TITLE
短信内容数组键、值兼容问题

### ISSUE THREAD

**Issue by inroading** [overtrue/easy-sms#173]
阿里云需要使用数组键值匹配，容联云通讯只使用数组值，不允许带键，带键提示"模板变量格式有误"
![](https://ws4.sinaimg.cn/large/006tKfTcly1g1l3wez0fwj30do09uq3j.jpg)
![](https://ws3.sinaimg.cn/large/006tKfTcly1g1l3ukn9zaj312c0fk772.jpg)
可否让容联云通讯忽略数组键

**Comment by overtrue** [comment]
@inroading 同时发送多个运营商的话，建议使用 README 上的自定义短信类来发送
