### ISSUE TITLE
阿里云签名错误

### ISSUE THREAD

**Issue by tszl004** [overtrue/easy-sms#183]
返回信息如下.看了一下你参考的文档是旧版的,不知道有没有新版SDK的支持?

Array
(
    [Message] => 签名不合法(不存在或被拉黑)
    [RequestId] => 6BD89DCE-8E0D-4A26-A4EF-C81605076BA3
    [Code] => isv.SMS_SIGNATURE_ILLEGAL
)

**Comment by thosege** [comment]
建议先检查下正式的阿里云签名配置信息是否存在，再顺着找下是否将正确的签名信息传入
