### ISSUE TITLE
云片国际短信, 支持的吗

### ISSUE THREAD

**Issue by yangqinjiang** [overtrue/easy-sms#196]
云片国际短信, 支持的吗
![image](https://user-images.githubusercontent.com/1914373/58062812-6d500f00-7bae-11e9-88a8-2948fa89bbe6.png)

**Comment by yangqinjiang** [comment]
云片的文档:
https://www.yunpian.com/doc/zh_CN/intl/single_send.html

**Comment by gdmec07150942** [comment]
我这边试过线上，调用云片短信接口，调用国内的域名地址（sms.yunpian.com）发送国外的号码短信，报了很多条curl超时错误
