### ISSUE TITLE
阿里大于ssl错误

### ISSUE THREAD

**Issue by dwdcth** [overtrue/easy-sms#20]
如题，修改了HasHttpRequest   getBaseOptions  自己解决了，请问有什么更好的方法。
 protected function getBaseOptions()
    {
        $options = [
            'base_uri' => method_exists($this, 'getBaseUri') ? $this->getBaseUri() : '',
            'timeout' => property_exists($this, 'timeout') ? $this->timeout : 5.0,
            'verify' => false,
        ];

        return $options;
    }

**Comment by overtrue** [comment]
其实更好的办法就是正确配置好证书

**Comment by dwdcth** [comment]
请问怎么把这些网站加到证书里

**Comment by overtrue** [comment]
https://easywechat.org/zh-cn/docs/troubleshooting.html#curl-60-SSL-certificate-problem-unable-to-get-local-issuer-certificate

**Comment by forecho** [comment]
更新一下 URL https://www.easywechat.com/docs/master/zh-CN/troubleshooting

**Comment by overtrue** [comment]
@forecho 哈哈 谢谢！
