### ISSUE TITLE
可以加上天瑞云的吗

### ISSUE THREAD

**Issue by phpervip** [overtrue/easy-sms#213]
tinree 
http://cms.tinree.com/static/index.html#/login
我们用的是这个。非常谢谢！

**Comment by overtrue** [comment]
欢迎提 PR

phpervip <notifications@github.com>于2019年9月5日 周四下午5:50写道：

**Comment by her-cat** [comment]
天瑞云要上传手持身份证照片才能用😓

**Comment by DickensGao** [comment]
可否提供一下测试账号或沙箱账号，我可以帮忙集成

**Comment by phpervip** [comment]
@successgo 非常谢谢！真是抱歉，我才看到，怎么联系你呢？我的QQ 2998658517
