### ISSUE TITLE
聚合短信的底层好像有问题，$config->get('app_key')拿不到key值

### ISSUE THREAD

**Issue by joeoeeee** [overtrue/easy-sms#223]
JuheGateway.php
![image](https://user-images.githubusercontent.com/30278704/65665664-a32a6600-e06e-11e9-8d5f-9cbab20eaf1f.png)
然后我只能改成这样才能使用：'key' => $config->get('app_key')?:env('JUHE_API_KEY');

**Comment by overtrue** [comment]
你的配置怎么写的啊

**Comment by joeoeeee** [comment]
> 你的配置怎么写的啊

1、.env
JUHE_API_KEY=c1db012a4f19d5be636db80c98dc83

Controller
$config = [
            // HTTP 请求的超时时间（秒）
            'timeout' => 5.0,
            // 默认发送配置
            'default' => [
                // 网关调用策略，默认：顺序调用
                'strategy' => \Overtrue\EasySms\Strategies\OrderStrategy::class,
                // 默认可用的发送网关
                'gateways' => [
                    'juhe',
                ],
            ],
            // 可用的网关配置
            'gateways' => [
                'errorlog' => [
                    'file' => '/tmp/easy-sms.log',
                ],
                'juhe' => [
                    'api_key' => env('JUHE_API_KEY'),
                ],
            ],
        ];
        $easySms = new EasySms($config);
        try {
            $res = $easySms->send(18037456400, [
                'content'  => '这是一个测试2！',
                'template' => '188299',
                'data' => [
                    'code' => 4321
                ],
            ]);
            dd($res);
        } catch (\Overtrue\EasySms\Exceptions\NoGatewayAvailableException $exception) {
            $message = $exception->getResults();
            dd($message);
        }

返回结果：100001，就是无key。
2、然后我去JuheGateway.php打印参数
![image](https://user-images.githubusercontent.com/30278704/65667358-28634a00-e072-11e9-846f-6dd54e3bca79.png)

打印结果：

array(5) {
--
  | ["mobile"]=>
  | string(11) "18037456400"
  | ["tpl_id"]=>
  | string(6) "188299"
  | ["tpl_value"]=>
  | string(15) "%23code%23=4321"
  | ["dtype"]=>
  | string(4) "json"
  | ["key"]=>
  | NULL
  | }

说明app_key丢失
3、我猜测是config.php的get方法有瑕疵，当然我没有细看源码，昨天开始上手测试的。
![image](https://user-images.githubusercontent.com/30278704/65667581-9a3b9380-e072-11e9-861c-ed6763e35556.png)
4、最后，谢谢大大！！

**Comment by overtrue** [comment]
1. 我文档里写的是叫 `app_key` 
2. 你的配置里写的是 `api_key`
