### ISSUE TITLE
互亿无限

### ISSUE THREAD

**Issue by lifeisgoodforall** [overtrue/easy-sms#23]
http://www.ihuyi.com/

可否加下

**Comment by lifeisgoodforall** [comment]
算了 这家太贵，

**Comment by mingyoung** [comment]
😂

**Comment by overtrue** [comment]
![image](https://user-images.githubusercontent.com/1472352/27621052-bd7e9340-5c00-11e7-9f94-2e8ed0028fae.png)

**Comment by motecshine** [comment]
qcloud  sms可以加上

**Comment by lifeisgoodforall** [comment]
好图，我写错了。 对的，有的。
非常方便
