### ISSUE TITLE
旦米渠道

### ISSUE THREAD

**Issue by hedeqiang** [overtrue/easy-sms#237]
哪位大佬计划支持一波旦米
想提交 pr ，能力有限，不敢提交

https://www.danmi.com/developer.html#smsSend

**Comment by successgo** [comment]
@hedeqiang 请问你能提供一下测试账号吗，我可以帮忙集成

**Comment by hedeqiang** [comment]
@successgo  现在没有了，离职了，目前没有旦米账号了

**Comment by hedeqiang** [comment]
之前 能力太弱 不敢提交 pr ，之前写过一点，https://github.com/hedeqiang/easy-sms/commit/6314f140787b328eddfef6526db325e386c23bfe    @successgo

**Comment by successgo** [comment]
@hedeqiang  写得挺好得呀

**Comment by successgo** [comment]
你写的这个网关我想你也经过测试，用过项目了吧，可以考虑下提交到这个项目PR。然后就可以考虑把这个 issue 关闭了。

另外，咱可以加个好友不

**Comment by hedeqiang** [comment]
具体时间久了 记不清了，应该是没有问题，只不过没有单元测试， 我的 微信/QQ： 760963254  @successgo
