### ISSUE TITLE
All the gateways have failed. You can get error details by `$exception->getExceptions()`

### ISSUE THREAD

**Issue by asen477** [overtrue/easy-sms#239]
奇怪，每次调用就是这个报错？

**Comment by loahi** [comment]
报上面同样的错误，
1、首先检查了短信网关配置是正确的，短信套餐未用完。
2、定位到问题出现在
guzzlehttp/guzzle/src/Handler/CurlFactory.php 185行
cURL error 28: Resolving timed out after 5000 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
电脑是可以正常上网的，直接在终端使用 curl 能获取到数据，修改 url 为百度首页，也是报解析超时错误，我估计这个问题和 easy-sms 没什么关系，应该是 php 的配置问题，我用的是 php 7.2.26版本，不知道要如何设置一下，还请指点一二？

**Comment by klmahua** [comment]
同样是这个错误，，也不知道是什么错误！！！

**Comment by overtrue** [comment]
很明显是你的 fpm 模式下 dns 解析失败啊
