### ISSUE TITLE
[建议]所有gateway均失败时，是否应当抛异常

### ISSUE THREAD

**Issue by littlehz** [overtrue/easy-sms#25]
我注意到 Messenger->send() 返回的是一个数组，包含了每次不同的gateway请求的结果。
是否考虑所有gateway全部返回失败时，抛出特定异常给业务层捕获？
毕竟有重试、或者随机取的机制，不抛异常的话，业务层很难确定所有接口均调用失败的情况（不知道是哪个key）

**Comment by overtrue** [comment]
嗯，对这个建议不错。我明天加上
