### ISSUE TITLE
配置文件的default 参数问题

### ISSUE THREAD

**Issue by strayjoke** [overtrue/easy-sms#250]
### 在 easy-sms/src/EasySms.php 文件 第 70行 
`$this->setDefaultGateway($config['default']);`
$config['default'] 应该期望是一个 *string* , 可是配置文件里 *default*  对应的是

` 'default' => [

        // 网关调用策略，默认：顺序调用
        'strategy' => \Overtrue\EasySms\Strategies\OrderStrategy::class,

        // 默认可用的发送网关
        'gateways' => [
            'yunpian', 'aliyun',
        ],
    ],`

这样如何设置defaultGateway? 求帮助

**Comment by zhou0818** [comment]
> ### 在 easy-sms/src/EasySms.php 文件 第 70行
> `$this->setDefaultGateway($config['default']);`
> $config['default'] 应该期望是一个 _string_ , 可是配置文件里 _default_ 对应的是
> 
> ` 'default' => [
> 
> ```
>     // 网关调用策略，默认：顺序调用
>     'strategy' => \Overtrue\EasySms\Strategies\OrderStrategy::class,
> 
>     // 默认可用的发送网关
>     'gateways' => [
>         'yunpian', 'aliyun',
>     ],
> ],`
> ```
> 
> 这样如何设置defaultGateway? 求帮助

我也是看到这里，而且没发现这里设置的defaultGateway实际的用处

**Comment by overtrue** [comment]
这里应该是遗留设计，我来改一下

**Comment by overtrue** [comment]
@strayjoke 这个的确是上一个版本遗留的设计，已经删除，如果需要设置默认网关，可以：

```php
'default' => [
    // 网关调用策略，默认：顺序调用
    'strategy' => \Overtrue\EasySms\Strategies\OrderStrategy::class,

    // 默认可用的发送网关
    'gateways' => [
        'yunpian', 'aliyun',  
    ],
],`
```

**Comment by strayjoke** [comment]
@overtrue 好的，我查看一下配置，看是需要重新配置。谢谢回复！
