### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223

### ISSUE THREAD

**Issue by maclechan** [overtrue/easy-sms#257]
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223

得 这样
COMPOSER_MEMORY_LIMIT=-1 composer require "overtrue/easy-sms"

**Comment by overtrue** [comment]
这是 composer 的问题

macle <notifications@github.com>于2020年6月20日 周六下午9:22写道：
