### ISSUE TITLE
guzzlehttp/guzzle 版本可否升级到7

### ISSUE THREAD

**Issue by ricebna** [overtrue/easy-sms#260]
现在有很多其他扩展包依赖的是guzzlehttp/guzzle7以上版本, 而 easy-sms 依赖的guzzlehttp/guzzle限定在7以下版本, 导致其他包安装失败.

**Comment by successgo** [comment]
https://github.com/overtrue/easy-sms/commit/141db806f6ec029be90e007dbf1fd360826b0efb 已解决

此问题可以关闭。

@ricebna @overtrue kindly ping

**Comment by overtrue** [comment]
@successgo 感谢！
