### ISSUE TITLE
百度云升级v2都废弃了,,建议升级v3支持一下

### ISSUE THREAD

**Issue by MIKOTO123** [overtrue/easy-sms#271]
如题:
百度云升级v2都废弃了,,建议升级v3支持一下
![image](https://user-images.githubusercontent.com/19549093/95650274-3537cc00-0b15-11eb-84a5-f80d46f85947.png)
如上图,我看这个项目里面的代码还是v2的认证版本,,,,已经不能用了估计...

**Comment by MIKOTO123** [comment]
为什么我图片链接发不出来- -!....
放个百度额api官网链接
https://cloud.baidu.com/doc/SMS/s/xkc1gs03p
百度那边说了:
  本次升级截止日期2020.8.20日24点，届时，将停止V2.0版本接口服务。为不影响您的正常使用，请您尽早安排接口升级，谢谢。

**Comment by overtrue** [comment]
新版以支持 #277

**Comment by MIKOTO123** [comment]
> 新版已支持 #277

我都自己写了个自定义网关搞定了,,,,,,你这个我回头用用看看如何,,,加油
