### ISSUE TITLE
composer 2.08    does not comply with psr-4 autoloading standard. Skipping.

### ISSUE THREAD

**Issue by 377123** [overtrue/easy-sms#285]
Class Overtrue\EasySms\Gateways\ModuyunGateway located in ./vendor/overtrue/easy-sms/src/Gateways/MoDuYunGateway.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by overtrue** [comment]
https://github.com/overtrue/easy-sms/pull/284

**Comment by overtrue** [comment]
已经修复了
