### ISSUE TITLE
安装 1.3.1版本提示大小写问题

### ISSUE THREAD

**Issue by gdmec07150936** [overtrue/easy-sms#289]
The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
    Update of overtrue/easy-sms failed

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

  [RuntimeException]
  The archive may contain identical file names with different capitalization (which fails on case insensitive filesys
  tems): ZipArchive::extractTo(/www/laravel/vendor/composer/8556c6fe/overtrue-easy-sms-85040b8/src/Gateways/ModuyunGa
  teway.php): failed to open stream: File exists

  [ErrorException]
  ZipArchive::extractTo(/www/laravel/vendor/composer/8556c6fe/overtrue-easy-sms-85040b8/src/Gateways/ModuyunGateway.p
  hp): failed to open stream: File exists

**Comment by overtrue** [comment]
已发布1.3.2
