### ISSUE TITLE
希望可以定时发送指定模板短信

### ISSUE THREAD

**Issue by lizuchun** [overtrue/easy-sms#291]
希望可以定时发送指定模板短信

**Comment by overtrue** [comment]
定时完全可以有 N 种做法啊，比如系统计划任务，这不属于一个功能包的范畴哦。

**Comment by lizuchun** [comment]
我是小白，刚下载了源码，现在还不会composer安装呢






李祖春
石材报价网


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "overtrue/easy-sms"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月26日(星期五) 中午12:38
收件人:&nbsp;"overtrue/easy-sms"<easy-sms@noreply.github.com&gt;;
抄送:&nbsp;"春暖花开"<363905372@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [overtrue/easy-sms] 希望可以定时发送指定模板短信 (#291)





 
定时完全可以有 N 种做法啊，比如系统计划任务，这不属于一个功能包的范畴哦。
