### ISSUE TITLE
关于阿里云短信SDK版本问题。

### ISSUE THREAD

**Issue by keeweihan** [overtrue/easy-sms#30]
当前阿里云短信的版本为：MNS PHP SDK V1.3.5 
https://help.aliyun.com/document_detail/32381.html?spm=5176.doc51929.6.685.XpRxws

请问超哥，easy-sms对阿里云的支持只到1.0呢？

**Comment by overtrue** [comment]
我不晓得你为啥突然来一句这个 SDK 的东西，我这个项目与这个 SDK 没有任何关系啊

**Comment by overtrue** [comment]
额。一个是接口版本，一个是 SDK 版本。。。

**Comment by overtrue** [comment]
文档在这里：https://help.aliyun.com/product/44282.html?spm=5176.doc55451.3.1.VU4vYy

**Comment by overtrue** [comment]
不是什么 MNS

**Comment by overtrue** [comment]
MNS 是阿里云消息服务，不是这里的短信服务。

**Comment by keeweihan** [comment]
额。。。感谢超哥，看到了你发的文档。

是我搞混淆了。

**Comment by overtrue** [comment]
哈哈
