### ISSUE TITLE
使用国际号码发送短信时，使用 PhoneNumber 处理手机号码会丢失手机号

### ISSUE THREAD

**Issue by jesse7866** [overtrue/easy-sms#314]
https://github.com/overtrue/easy-sms/blob/58e405f030574547d00710fc9538d8e0867620e2/src/PhoneNumber.php#L37-L51

https://github.com/overtrue/easy-sms/blob/58e405f030574547d00710fc9538d8e0867620e2/src/Gateways/QcloudGateway.php#L60

如果传手机区号了，那么 `getIDDCode` 只会获取区号，就没有手机号码了，发送短信会提示参数有误

使用版本 V2.0.1

**Comment by overtrue** [comment]
举例子看一下？

**Comment by jesse7866** [comment]
例子：

**Comment by jesse7866** [comment]
例子：

```php
app('easysms')->send(new PhoneNumber($phone, 86), new RegisterMessage($code));
```

**Comment by jesse7866** [comment]
多谢帮忙处理 👍

**Comment by overtrue** [comment]
@jesse7866 客气了。
