### ISSUE TITLE
腾讯云发送示例，配置中'secret_id'的值指的是什么？腾讯云短信按照示例发送失败

### ISSUE THREAD

**Issue by bmkj** [overtrue/easy-sms#324]
腾讯云发送示例，配置中'secret_id'的值指的是什么？
腾讯云短信按照示例发送失败
上一个版本没问题

**Comment by kvnZero** [comment]
2.0以上的版本使用V3版本签名需要使用SecretId
签名文档地址：[申请安全凭证
](https://cloud.tencent.com/document/api/382/52072#.E7.94.B3.E8.AF.B7.E5.AE.89.E5.85.A8.E5.87.AD.E8.AF.81)
文档里可跳转控制台，去控制台重新申请一个密钥就好了。 不使用V3签名需要使用旧V1的话在composer.json将包版本固定^1
