### ISSUE TITLE
阿里云发送包含有~特殊符号的短信时，因签名不匹配，导致发送失败

### ISSUE THREAD

**Issue by AnneWong** [overtrue/easy-sms#326]
Client error: `GET http://dysmsapi.aliyuncs.com?` resulted in a `400 Bad Request` response:"Message":"Specified signature is not matched with our calculation.  (truncated...)
[阿里云短信请求签名文档地址](https://help.aliyun.com/document_detail/101343.html)
![构造待签名的请求串截图](https://user-images.githubusercontent.com/32324937/156344014-4381d166-d1aa-41e0-85cb-c0acdbb70a81.png)

**Comment by overtrue** [comment]
https://github.com/overtrue/easy-sms/releases/tag/2.1.1
