### ISSUE TITLE
貌似腾讯云不能用了

### ISSUE THREAD

**Issue by QQOQ** [overtrue/easy-sms#332]
一直提示The value type of parameter `SmsSdkAppId` is not valid

**Comment by kvnZero** [comment]
没问题呀，业务上还在正常跑。是不是传值错误了？

**Comment by QQOQ** [comment]
> 没问题呀，业务上还在正常跑。是不是传值错误了？

sdk_app_id=字符串类型。
如果是整型就报这个错，有点坑这个腾讯
