### ISSUE TITLE
特意注册帐号来吐槽的，这轮子真傻

### ISSUE THREAD

**Issue by y9000** [overtrue/easy-sms#333]
从laravel社区了解的这个组件，之前都不发评论的，特意注册帐号来吐槽的，但是看完这个轮子后，我是服了，都不知道哪来的自信说是优秀的开源项目

用开源的组件就是方便快捷，有人可能会说：开源的，知足吧，拿来主义还那么多话。
但是你们好好想想，这弄个半成品，然后迷之自信说优秀，擦

发短信的场景
有发送，肯定有验证，包括发送次数限制和日志存储，star：2.8K，fork：510,试想一下，全都要再完成另一半验证

你看看这个https://github.com/toplan/laravel-sms，多学学吧

**Comment by overtrue** [comment]
感谢大佬批评！
