### ISSUE TITLE
SendCloud 时间戳无效

### ISSUE THREAD

**Issue by fxxxf** [overtrue/easy-sms#35]
SendCloud 服务端时间戳为 13 位 JS 时间戳，所以 SendCloud 发送时会返回：时间戳无效，与服务器时间超过60000毫秒。

SendCloud 文档提示需要通过接口获取时间戳：http://www.sendcloud.net/smsapi/timestamp/get

故可以考虑注释掉 SendcloudGateway.php 46 行 或者 补全 13 位时间戳。

**Comment by overtrue** [comment]
感谢！
