### ISSUE TITLE
阿里云镜像为什么不同步这个包了？我这边直接就找不到

### ISSUE THREAD

**Issue by indiboy** [overtrue/easy-sms#361]
Problem 1
    - Root composer.json requires overtrue/easy-sms 3.0.0 (exact version match: 3.0.0 or 3.0.0.0), found overtrue/easy-sms[dev-master, 0.0.1, ..., 0.0.10, 1.0.0, ..., 1.x-dev, 2.0.0, ..., 2.6.0] but it does not match the constraint.

**Comment by overtrue** [comment]
阿里云的镜像我没记错已经停止维护三年多了吧
