### ISSUE TITLE
SendCloud 替换变量格式错误

### ISSUE THREAD

**Issue by fxxxf** [overtrue/easy-sms#37]
当 SendCloud 使用模板无变量替换时，发送参数 vars 为字符串  `"vars" => "[]"`  导致 SendCloud 报错：替换变量格式错误。

可考虑过滤掉空值 或 为空情况下 `formatTemplateVars` 返回数组：
``` php
if (empty($vars)) {
    return $formatted;
}
```

**Comment by overtrue** [comment]
靠，这么坑...

**Comment by overtrue** [comment]
@fxxxf 能不能帮忙把其它问题一起测完给个反馈，因为我没有账号，申请审核太慢

**Comment by fxxxf** [comment]
哈哈，没了没了。
我也是刚开始使用 SendCloud，还有问题的话我汇总下，及时反馈。

**Comment by overtrue** [comment]
哈哈

**Comment by overtrue** [comment]
@fxxxf 如果空的话传啥值？null?

**Comment by overtrue** [comment]
@fxxxf 你把 78 行改成：

```php
return json_encode($formatted, JSON_FORCE_OBJECT);
```
试试

**Comment by fxxxf** [comment]
@overtrue 模板审核中，我稍后试下。 刚试的时候，空数组是可以的。

**Comment by overtrue** [comment]
好

**Comment by fxxxf** [comment]
@overtrue 试了下，添加 JSON_FORCE_OBJECT 可以。

**Comment by overtrue** [comment]
好的
