### ISSUE TITLE
超哥,短信这个可以加上队列么

### ISSUE THREAD

**Issue by uniteweiwei** [overtrue/easy-sms#38]
RT

**Comment by overtrue** [comment]
由于各自的框架与开发环境的不同，建议在自己应用里调用时使用队列，比如在 Laravel 里可以写到 Job 里，然后 dispatch 这样就好了。因为每个人自己的应用队列环境不一样，我内置的话别人不一定能用，单一职责原则，所以应该是在这个组件之上去包裹队列。
