### ISSUE TITLE
现在阿里云的短信服务已合并到了消息服务

### ISSUE THREAD

**Issue by wangjiaqi** [overtrue/easy-sms#39]
![20170724134005](https://user-images.githubusercontent.com/1821532/28509546-a55e70ee-7075-11e7-87d8-eec3f520013f.png)

现在阿里云的短信服务已合并到了消息服务，貌似不能用啊

**Comment by overtrue** [comment]
错误原因是？$e->result

**Comment by wangjiaqi** [comment]
![20170725020400](https://user-images.githubusercontent.com/1821532/28537557-e7336610-70dd-11e7-8d15-05a8e60d486a.png)

@overtrue 说是“没有访问权限”。但是我已添加了短信服务的权限。我的问题是，阿里云已经把短信服务整合到了消息服务里，我无法在阿里云的控制台中进入短信服务的管理面板，而会被提示并重定向到消息服务里。我把消息服务里创建的短信签名、模板用在 `easy-sms` 上，是不是不能这样搞？

**Comment by wangjiaqi** [comment]
![20170725022911](https://user-images.githubusercontent.com/1821532/28538646-7f6d7148-70e1-11e7-8122-726e0db10c61.png)

这篇[公告](http://helpcdn.aliyun.com/document_detail/51077.html)目前已被阿里云从官网撤下，我是从百度快照里截的图

也就是说 `easy-sms` 的阿里云网关只能是2017年3月31日之前开通了阿里云短信服务的账号才能用，之后开通的那是阿里云消息服务，消息服务的短信功能时无法使用 `easy-sms` 的？

**Comment by overtrue** [comment]
刚才去阿里云试了一下，可以正常开通啊，感觉是这个决策后来又没有实施吧
