### ISSUE TITLE
阿里大于已被整合到阿里云·云通信，新用户已无法使用阿里大于短信接口

### ISSUE THREAD

**Issue by this-BaiShi** [overtrue/easy-sms#41]
配置阿里大于信息的时候一直找不到拿到app key 的地方，问了大于的客服才知道，阿里大于已被整合到阿里云的云通信里，新注册用户无法登陆老的阿里大于平台。

> 提个issue记录一下这个坑，或是请教一下作者有没有可以兼容的办法😁

**Comment by overtrue** [comment]
@this-BaiShi 用 aliyun 那个吧，不用大于了，他们应该会逐渐关掉大于

**Comment by xuhuaiqu** [comment]
不在维护alidayu了啊。还是有不少人在用的。

**Comment by overtrue** [comment]
@xuhuaiqu 没说不维护啊，官方关了入口，代表服务肯定会逐渐下线嘛。

**Comment by this-BaiShi** [comment]
@overtrue  好的，我已经切换到aliyun了，
