### ISSUE TITLE
超哥 求助

### ISSUE THREAD

**Issue by DanceSmile** [overtrue/easy-sms#53]
用的是阿里云的短信服务，同一个手机号码，上午可以正常发送并且接受到短信。
然后到晚上发送这个手机  就会报错，别的手机号码是正常的

NoGatewayAvailableException in Messenger.php line 88:
All the gateways have failed.

**Comment by moore0903** [comment]
什么问题导致的,有时候也出现了这个

**Comment by moore0903** [comment]
运营商返回的错误,在发送的时候捕获一下,然后记录下来.

**Comment by DanceSmile** [comment]
是平台限制了  24小时 只能10条短信
阿里云

**Comment by PandaVPN** [comment]
> 是平台限制了 24小时 只能10条短信
> 阿里云

怪不得，还以为能自己配置限制条数呢

**Comment by JasonZsl6** [comment]
> 是平台限制了 24小时 只能10条短信
> 阿里云

怪不得，我还以为能自己限制短信条数

**Comment by JasonZsl6** [comment]
111

**Comment by PandaVPN** [comment]
您好，请问您现在需要什么帮助呢？


Best Regards,
————————————————
PandaVPN Team
