### ISSUE TITLE
如果配置更强大一点就更好了

### ISSUE THREAD

**Issue by johson** [overtrue/easy-sms#54]
建议把短信平台的URL也放到配置文件里。因为好多公司都用的是二级代理（比如我们公司），虽然也是创蓝的文档，但是请求的地址却不是同一个。

**Comment by motecshine** [comment]
fork && make a new branch && PR. just do it

**Comment by imdgr** [comment]
不是可以自定义网关吗

**Comment by gaodacheng** [comment]
同为一个产品吗？
