### ISSUE TITLE
我对“添加对融云的支持”的疑问

### ISSUE THREAD

**Issue by gaodacheng** [overtrue/easy-sms#57]
请问有没有什么注意事项，当我提交PR的时候？

另外，我将要添加的RongcloudGateway中，默认是发送短信功能。不过，通过在data[]中添加action扩展额外的功能，比如验证短信验证的正确性，因为这个是由融云接口提供的，不知道这样有没有违背框架库的东西？

**Comment by overtrue** [comment]
例如？

**Comment by gaodacheng** [comment]
您有空了，看一下我的PR，悉心聆听您的意见。

**Comment by gaodacheng** [comment]
我现在关闭这个issue了。
