### ISSUE TITLE
请问如何同时使用多家服务商

### ISSUE THREAD

**Issue by gdc5p** [overtrue/easy-sms#68]
1. 首先问一下，该库定位是不是可以同时使用多家服务商发送短信？

2. 其次，再问一下，如何处理每一家服务商对应的模板ID不同的问题（如果是这家服务商需要采用模板发送短信）的？

我想，关于模板ID的处理好像有点问题吧

**Comment by overtrue** [comment]
请详细阅读使用说明。

1. 在配置中已经写了如何同时启用多家服务商：
```php
// 默认可用的发送网关
        'gateways' => [
            'yunpian', 'aliyun', 'alidayu',
        ],
```

2. 如何处理每一家服务商对应的模板ID不同的问题

网关会自己判断用模板还是用内容，你只需要在 Message 设置对应的内容与模板即可。

在消息对象里有 `getData`， `getTemplate`， `getContent` 等方法，都有一个参数是当前运行的网关实例，你需要根据当前的网关实例来返回对应的内容或者模板。
