### ISSUE TITLE
可不可以在Gateway里添加一个getName方法

### ISSUE THREAD

**Issue by gdc5p** [overtrue/easy-sms#69]
用以返回当前网关的名字。

**Comment by overtrue** [comment]
直接用类名吧：  get_class($gateway) === XXXGategay::class

**Comment by gdc5p** [comment]
用类名，需要提前在前面一个一个的都引入各大网关。

如果可以有getName方法，可以直接动态调用这个方法，然后加载相应网关下的模板ID等配置信息。因为配置的时候可以方便的按照这个约定来。

您再考虑一下这个可行性，我可以完善这个的，我有时间。

**Comment by overtrue** [comment]
我是觉得这样多了一道记忆成本，大家还得记每个网关的 name, 而不是直接使用类名这样直接

**Comment by gdc5p** [comment]
其实网关的名称，我就打算采用gateway的前辍，并且小写的形式。

这样真得不是更加方便吗

**Comment by overtrue** [comment]
那你来加吧，我是觉得差不多

**Comment by gdc5p** [comment]
Ok，it is my pleasure.

**Comment by gdc5p** [comment]
已经合并进主分支，我要关闭这个issue.
