### ISSUE TITLE
aliyun不能用啊

### ISSUE THREAD

**Issue by istheprince** [overtrue/easy-sms#83]
按照文档配置好了,就是不行,目前用的是阿里官方的sdk,想用这个扩展包,但是不知道哪里出了问题,config都正确配置了,template和data也写了,就是不行呢...

**Comment by gdc501** [comment]
阿里云目前有两个版本的接口，请确定你的账号是阿里之前的阿里大鱼，还是阿里通信？

**Comment by istheprince** [comment]
使用的阿里通信,配置里`access_key_id`,`access_key_secret`,`sign_name`都配置好了,在`message`里`template`也传了,但是会提示`All the gateways have failed.`修改`AliyunGateway.php`里`ENDPOINT_URL`常量为现在项目中用的服务结点会正常报错(定义的错误消息),debug如下
```
{
    "message": "短信发送异常",
    "status_code": 500,
    "debug": {
        "line": 173,
        "file": "D:\\project\\laravel\\api.test.com\\vendor\\dingo\\api\\src\\Http\\Response\\Factory.php",
        "class": "Symfony\\Component\\HttpKernel\\Exception\\HttpException",
        "trace": [
```

**Comment by gdc501** [comment]
@istheprince 

> 使用的阿里通信,配置里access_key_id,access_key_secret,sign_name都配置好了,在message里template也传了,但是会提示All the gateways have failed.

这里有个排查问题的路线：

[文档](https://github.com/overtrue/easy-sms#%E8%BF%94%E5%9B%9E%E5%80%BC) 中指出，

> 如果所选网关列表均发送失败时，将会抛出 Overtrue\EasySms\Exceptions\NoGatewayAvailableException 异常，你可以使用 $e->results 获取发送结果。

你打印这个结果看下。

**Comment by istheprince** [comment]
我不知道在哪里使用$e->results,能告诉我吗?我用的比较笨的方法,在NoGatewayAvailableException.php里的构造方法里把results打印了出来,是aliyun返回的多维数组
```
{"aliyun":{"status":"failure","exception":{"raw":{"Message":"触发小时级流控Permits:5","RequestId":"EFB5A5E4-5899-45FB-928E-56A9D25B9392","Code":"isv.BUSINESS_LIMIT_CONTROL"}}}}
```
是不是用$e->results就能直接获取多维数组里Message返回的错误呢?请问如何直接获取Message里的数据呢?谢谢

**Comment by gdc501** [comment]
@istheprince 

> 我不知道在哪里使用$e->results,能告诉我吗?

对于异常 $e，直接获取的。

不管怎样，你获取到这个数据了。

> "Message":"触发小时级流控Permits:5"

这个提示，说明发送次数多过了。1小时内只能发送5次。

> 对了,这个错误是因为我测试发送短信太多被限制了...

是得。

**Comment by gdc501** [comment]
本 issue 可以关闭了。
