### ISSUE TITLE
如果抛出异常我要怎么捕获错误信息？

### ISSUE THREAD

**Issue by dullme** [overtrue/easy-sms#85]
我现在使用的阿里云，出现 All the gateways have failed. 我打印出错误信息是请求频繁了，有没有方便的方法获取这个错误信息？
{"aliyun":{"status":"failure","exception":{"raw":{"Message":"触发小时级流控Permits:5","RequestId":"A324EFD4-3162-4354-9D39-24AE4EE6871F","Code":"isv.BUSINESS_LIMIT_CONTROL"}}}}

我现在打印这个信息是 return $e->results;如果我只想获取Message 信息要怎么做 是不是所有的短信通道都可以这么获取？

**Comment by overtrue** [comment]
https://github.com/overtrue/easy-sms#%E8%BF%94%E5%9B%9E%E5%80%BC
https://github.com/overtrue/easy-sms/blob/master/src/Exceptions/GatewayErrorException.php#L22

```php
$e->raw; // {"Message": "触发小时级流控Permits:5"}
$e->raw['Message']; // 触发小时级流控Permits:5
```

**Comment by dullme** [comment]
```
try{
        return $easySms->send(13188888888, [
            'content'  => '您的验证码为: 6379',
            'template' => 'SMS_126335396',
            'data' => [
                'code' => 6379
            ],
        ]);
    } catch (\Overtrue\EasySms\Exceptions\NoGatewayAvailableException $e) {

        return $e->raw['Message'];;
    }
```
报这个错：
ErrorException (E_NOTICE)
Undefined property: Overtrue\EasySms\Exceptions\NoGatewayAvailableException::$raw

**Comment by overtrue** [comment]
NoGatewayAvailableException 里的属性是 `results` 存储着多个网关的错误，比如有两个网关都失败时，你可以拿到每一个的错误，你应该遍历  `$e->results` 得到一个数组，数组里的 `exception` 就是该网关的错误消息：

```php
try{
        return $easySms->send(13188888888, [
            'content'  => '您的验证码为: 6379',
            'template' => 'SMS_126335396',
            'data' => [
                'code' => 6379
            ],
        ]);
    } catch (\Overtrue\EasySms\Exceptions\NoGatewayAvailableException $e) {
        foreach($e->results as $result) {
              if ($result['status'] != 'success') {
                      return $result['exception']->raw['Message']; 
              }
        }
        return $e->raw['Message'];
    }
```

**Comment by overtrue** [comment]
或者如果你只用一个网关，可以考虑把上面的 foreach 部分改成：

```php
return $e->results['aliyun']['expcetion']->raw['Message'];
```

**Comment by overtrue** [comment]
参考：https://github.com/overtrue/easy-sms#%E8%BF%94%E5%9B%9E%E5%80%BC

**Comment by mojiajuzi** [comment]
@overtrue 
the array key is `exception` not `expcetion` 
```php
return $e->results['aliyun']['expcetion']->raw['Message'];
```

**Comment by overtrue** [comment]
@mojiajuzi 🤣 Fixed.
