### ISSUE TITLE
创蓝的应该不能使用了吧

### ISSUE THREAD

**Issue by bostin** [overtrue/easy-sms#89]
[https://www.253.com/api-docs-97](https://www.253.com/api-docs-97)
接口文档显示用户名和密码参数应该是account和password
我看你源码里面是un和pw

**Comment by motecshine** [comment]
你可以提个 Pull Request

**Comment by bostin** [comment]
如果有时间的话，来支持一下 😆

**Comment by pinguo-tonganping** [comment]
被改的不能用了。 哎。

**Comment by pinguo-tonganping** [comment]
被 改之前是能使用的， 我跟创蓝的开发对过。

**Comment by overtrue** [comment]
@pinguo-tonganping 能不能不要只知道抱怨？按文档来确实需要这样改啊：https://zz.253.com/v5.html#/api_doc

**Comment by overtrue** [comment]
创蓝这帮开发者文档是随便改的么，我也知道第一版与现在的不一样
