### ISSUE TITLE
云片报错捕获不到异常

### ISSUE THREAD

**Issue by xujunjiepk** [overtrue/easy-sms#90]
GuzzleHttp\Exception\ClientException #400
Client error: `POST https://sms.yunpian.com/v2/sms/single_send.json` resulted in a `400 Bad Request` response

**Comment by overtrue** [comment]
请提供你捕获的代码

**Comment by overtrue** [comment]
请升级到 https://github.com/overtrue/easy-sms/releases/tag/1.0.7 版本解决。

**Comment by xujunjiepk** [comment]
感谢 我明天试试

**Comment by xujunjiepk** [comment]
'errorlog' => [
		            'file' => '/tmp/easy-sms.log',
		        ], 
这个怎么才能记录日志啊
