### ISSUE TITLE
用阿里云的时候提示手机号不可用要这样写

### ISSUE THREAD

**Issue by jaydenluo** [overtrue/easy-sms#99]
$number = new PhoneNumber(13188888888, 00);
        try {
            $result = $easySms->send( $number, [
                // 'content' => '您的验证码为: 6379',
                'template' => 'SMS_136335001',
                'data' => [
                    'status' => 'status-test',
                    'remark' => 'remark-test',
                ]]
            );

**Comment by overtrue** [comment]
@jaydenluo 麻烦试一下 dev-master 版本。
